# Generated by Django 4.1.3 on 2023-02-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childmissingapp', '0002_alter_police_badge_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='complainant_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('child_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('identification', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('staus', models.CharField(max_length=50)),
                ('report', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('child_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('identification', models.TextField()),
                ('Details', models.TextField()),
                ('staus', models.BooleanField(default=False)),
                ('report', models.CharField(max_length=255)),
            ],
        ),
    ]
